---
name: Bug Report
about: Report a bug to help us improve
title: '[Bug]: '
labels: bug, P2
assignees: ''
---

## Description
A clear and concise description of what the bug is.

## Steps to Reproduce
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error

## Expected Behavior
A clear and concise description of what you expected to happen.

## Actual Behavior
A clear and concise description of what actually happened.

## Screenshots
If applicable, add screenshots to help explain your problem.

## Environment
- OS: [e.g. macOS, Windows, Linux]
- ocgui version: [e.g. 0.1.0]
- OpenCode CLI version: [e.g. 1.0.0]
- Node.js version: [e.g. 20.10.0]

## Additional Context
Add any other context about the problem here.

## Possible Solution
If you have suggestions on a fix for the bug, please describe it here.
