---
name: Feature Request
about: Suggest a new feature or enhancement
title: '[Feature]: '
labels: enhancement, P3
assignees: ''
---

## User Story
As a [type of user], I want [some goal] so that [some reason].

## Problem Statement
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## Proposed Solution
A clear and concise description of what you want to happen.

## Alternatives Considered
A clear and concise description of any alternative solutions or features you've considered.

## Acceptance Criteria
- [ ] Given [context], when [action], then [outcome]
- [ ] Given [context], when [action], then [outcome]

## Additional Context
Add any other context or screenshots about the feature request here.

## Related Features
List any related features or dependencies that should be considered.
